name: Build and QC for rustsim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build-mac:
    name: Build for Mac x86_64 and aarch64
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          command: build

  build-manylinux:
    name: Build for Linux x86_64 and aarch64
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          command: build

